<TwoLineListItem>:
	text:root.username
	secondary_text:root.about
	ImageLeftWidget:
		source:root.source
<TwoLineIconListItem>:
	text:root.action
	secondary_text:root.description
	IconLeftWidget:
		icon:root.icon
<SettingScreen>:
	MDBoxLayout:
		orientation:'vertical'
		TwoLineListItem:
			source:'assests/images/19.jpg'
			text:'Liam'
			secondary_text:'if life is journey where is the destination'
		TwoLineIconListItem:
			action:



		
